# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue here! ğŸ’–

  Be sure to follow the issue template. Then the
  issue will be worked on in no time. ğŸ‘

# Comment to be posted on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Thanks for opening this pull request! ğŸ’– 

  Please check out the [code of conduct](https://github.com/kai-tub/latex-beamer-pure-minimalistic/blob/master/CODE_OF_CONDUCT.md)
  and the [contributing guidelines](https://github.com/kai-tub/latex-beamer-pure-minimalistic/blob/master/CONTRIBUTING.md).

  Although, you probably have read it already. ğŸ˜

# Comment to be posted on PR merges from first time contributors in your repository
firstPRMergeComment: |
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
  We here are proud of you and your accomplishment ğŸ†.
  
  ![dog-image](https://i.imgflip.com/133h3v.jpg)
