name: Upload Assets

on:
  release:
    types: [ published ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  jobs:
    upload_assets:
      name: Create/Upload assets
      runs-on: ubuntu-latest
      steps:
        - name: Set up Git
          uses: actions/checkout@v2
        - name: Get demo.pdf
          run: wget https://github.com/kai-tub/latex-beamer-pure-minimalistic/wiki/demo.pdf -O demo.pdf
        - name: Get release
          id: release
          uses: bruceadams/get-release@v1.2.0
        - name: Create archives
          run: |
            zip pureminimalistic.zip *.sty demo.tex demo_bib.bib logos/*
            tar -cf pureminimalistic.tar.gz *.sty demo.tex demo_bib.bib logos/*
        - name: Upload zip asset
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.release.outputs.upload_url }}
            asset_path: ./pureminimalistic.zip
            asset_name: pureminimalistic.zip
            asset_content_type: application/zip
        - name: Upload tar.gz asset
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.release.outputs.upload_url }}
            asset_path: ./pureminimalistic.tar.gz
            asset_name: pureminimalistic.tar.gz
            asset_content_type: application/tar.gz
        - name: Upload demo.pdf
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.release.outputs.upload_url }}
            asset_path: ./demo.pdf
            asset_name: demo.pdf
            asset_content_type: application/pdf
        